apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oa3fvrl6i-python
  janus-idp.io/tekton: oa3fvrl6i-python
  backstage.io/kubernetes-id: oa3fvrl6i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oa3fvrl6i-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
